### PR TITLE
Add GitHub workflow and update Golang build

### PR DESCRIPTION
**Pull request by karl-johan-grahn**

### CODE REVIEW

**Comment by karl-johan-grahn** [comment]
@etiennetremel please review 🙏

**Comment by etiennetremel** [comment]
Sorry @karl-johan-grahn, I'm not a maintainer anymore, my access was revoked a couple of month ago.

**Comment by karl-johan-grahn** [comment]
ContainerSolutions has zero members 🤔 Is this organization entirely abandoned?

**Comment by karl-johan-grahn** [comment]
@luebken @ppaltmann @ivuk ?

**Review by gusfcarvalho — APPROVED** [review]

**Pull request merged**
